pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    stages {
        stage('Declarative: Checkout SCM') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: '
https://github.com//GUMMASAISINDHU/java-maven-app']]])
            }
        }
        stage('Choose Branch') {
            steps {
                script {
                    branches = bat(returnStdout: true, script: 'git ls-remote --heads origin').trim().split("\\r?\\n")
                    branchNames = branches.collect { it.split("\\s+")[1].replaceAll("refs/heads/", "") }
                    echo "Available branches: ${branchNames}"
                }
            }
        }
        stage('Checkout') {
            steps {
                echo 'Checking out code...'
                checkout scm
            }
        }
        stage('Build and Test') {
            steps {
                echo 'Building and Testing...'
                bat 'mvn clean package'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                // Add your deployment steps here
            }
        }
    }
    post {
        always {
            echo 'This will always run'
        }
        success {
            input 'Deploy to production?'
        }
    }    
}
